### ISSUE TITLE
Tagslam needs additional include to build with clang-12 on ubuntu 20.04

### ISSUE THREAD

**Issue by Brian-Acosta** [berndpfrommer/tagslam#32]
Issue: I get the following error building tagslam on ubuntu 20.04 using clang-12 and clang++-12

```
/home/brian/tagslam_root/src/tagslam/include/tagslam/sync_and_detect.h:146:46: error: cannot use incomplete type 'rosbag::View' as a range
      for (const rosbag::MessageInstance &m: *view) {
                                             ^
/opt/ros/noetic/include/rosbag/bag.h:96:7: note: forward declaration of 'rosbag::View'
class View;
```

Solution: add `#include <rosbag/view.h>` [here](https://github.com/berndpfrommer/tagslam/blob/ab468a8e4c9551a4f018a2d3a7560d4ed8a5e29b/include/tagslam/sync_and_detect.h#L19)

**Comment by berndpfrommer** [comment]
I stopped supporting ROS1, closing this issue.
